# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Today I Learned
email: karl@bearded.sexy
description: > # this means to ignore newlines until "baseurl:"
  Today I Learned. A searchable knowledge base of markdown notes forming
  categories usable like cheat sheets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://til.karlbowden.com" # the base hostname & protocol for your site
twitter_username: karlbowden
github_username:  agentk
permalink: /:categories/:title/
exclude: ['Gemfile', 'Gemfile.lock']
timezone: Australia/Sydney

gems:
  - jekyll-lunr-js-search
  - jekyll-paginate
  - jekyll-sitemap

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions:
    - tables
    - autolink
    - strikethrough
    - space_after_headers
    - with_toc_data
    - fenced_code_blocks
    - no_intra_emphasis
    - footnotes
    - smart

lunr_search:
  js_dir: assets/scripts

